### ISSUE TITLE
Update packages to pypi

### ISSUE THREAD

**Issue by Seraf** [concentricsky/django-tastypie-swagger#67]
Hello,

Is it possible to give access to few contributors to the pypi to update the package according to new releases ?

Actually users will install https://pypi.python.org/pypi/django-tastypie-swagger .2 version and I need fixes in .3 ...

Thanks !

**Comment by fellowshipofone** [comment]
Feels like the package is now 1yr out of date! any chance it could be updated?

**Comment by johnraz** [comment]
Looking at the state of tastypie, maybe its time to turn to django-rest-framework and just give up on this ?

**Comment by fellowshipofone** [comment]
hahahaha. DRF is a little bit like the Drupal of Rest framework. I was hoping to migrate to Tastypie really...

**Comment by johnraz** [comment]
@fellowshipofone Not so sure to get how you would compare something like Drupal which is a full fledged cms / frameworkish solution to DRF which is  just an extension to build apis on top of django, even if 3.0 aims to be a bit more than that... 

Anyway, I don't believe you will ever match the feature set in DRF with Tastypie, and I've been using both in production on quite big projects.

And I don't see either how going from DRF to Tastypie is the path to follow, it just sounds plain wrong to me to go from something hugely maintained and active to a barely maintained project.
All that said, it's probably not the place to discuss it anyway, I was just throwing my 2 cents ;-)

Back to the main subject, I don't believe much will happen as @krimkus is hard to reach...

@fellowshipofone, if you still believe you must go with Tastypie, I would suggest that you start a fork or at least a side package on pypi for this project ;-)

Cheers !

**Comment by fellowshipofone** [comment]
I did not mean to troll the subject :) 

You're right that you can't compare both, but I meant to compare DRF to other rest framworks the same way you'd compare Drupal to other CMS; 

I have used both DRF and Tastypie in production too, and I enjoy the coding style of Tastypie more. Support is not great, but that's something we can change, although I agree it's easier to stick to DRF ;)

Thanks...

**Comment by krimkus** [comment]
Hey @johnraz, I am indeed hard to reach. I am no longer with Concentric Sky, so I don't have access to manage this repo or push to PyPi. If that is needed, please contact the current owners of the project, and I'm sure they can help you out. 

That said, I would highly recommend deprecating this altogether in favor of DRF. If anyone is actually interested in contributing or updating this library, they should take control of the repo and PyPi updates.

**Comment by johnraz** [comment]
@fellowshipofone : you did not mean to but you must agree the tone was a bit ambiguous ;-) Also on the "we can change things" argument, sure we can, but not without a lot of time to invest in the project to reach the quality of DRF.

@krimkus : I have no idea who would be the owned @concentricsky/owners  ? Do you ?

Anyway, as far as I'm concerned, I don't plan to go back to Tastypie any time soon, and neither do I plan to contribute much here. I still have my commit rights to the repo and will be glad to help merge PR and stuffs, until we find someone to take the lead. 

Again, maybe it is time to start a fork ;-)

**Comment by fellowshipofone** [comment]
Definitely something to think about. I think our team would be willing to support a project that is more lightweight than DRF, but just like I think you mean, I am not sure it is worth it...

Also, Tastypie is working quiet well, with a few things we could change, but the discussion here is on tastypie-swagger...

Thanks for the input, I'll comment again if I fork the repo. The master version does not work with our Django 1.7 Python 2.7 project either, so that's not super encouraging :palm_tree:

**Comment by dokkaebi** [comment]
Hi @fellowshipofone , @johnraz , 

I'm not sure what our plans are for this package moving forward, but you're right in noticing that it's pretty far out of date. We are mostly using DRF these days as well.

I'll run it by the rest of the team on Monday. Meanwhile, is there anything specific you're looking for or are we just talking about getting the open pull requests merged and testing with 1.7?

**Comment by fellowshipofone** [comment]
Thanks for the reply. As far as I'm concerned, I just started looking at the project on Thursday and I noticed the `master` branch does not work with our setup of Django 1.7, maybe due to the `APPEND_SLASH` settings.

And obviously, a lot of commits are on the repository since the last PyPi release.

**Comment by oppianmatt** [comment]
I know we all should be using DRF instead, but some of us are stuck on legacy projects. We all know about the current attacks on github so having to install swagger from github on requirements is breaking a few builds. All someone needs to do is just upload the latest version to pypi and then we can deploy from that. 

https://pypi.python.org/pypi/django-tastypie-swagger

**Comment by fellowshipofone** [comment]
We're back to DRF only, since this project is obviously not going to move anymore. But thanks :)

**Comment by oppianmatt** [comment]
maintainers should just paste in the pypi creds and we could upload a new version from the source.

**Comment by dokkaebi** [comment]
Hey all, sorry about the long turnaround.

I've since taken some time to get the library up and running with a 1.7 project. The tip of master works for me in that context, so if you're having trouble let's open a ticket specific to that issue. Meanwhile I'm going to bump the version and update pypi. I make no claims that the incoming 0.1.4 is perfect, but at least it's closer than 0.1.3.

**Comment by johnraz** [comment]
@dokkaebi Awesome ! thanks a lot ;-)
